import Head from 'next/head'
import Image from 'next/image'
import styles from '../../styles/Home.module.css'
export default function Table() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
          <h1>fruit</h1>
            <div className="max-w-2xl mx-auto bg-write text-black w-screen">

	  <div className="relative overflow-x-auto shadow-md sm:rounded-lg">
		<div className="p-4">
            <button className="bg-green-400 w-36 h-16">Add user</button>
		
			<div className="relative mt-1">
			
				<input type="text" id="table-search" className="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-80 pl-10 p-2.5  dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" placeholder="Search here"/>
        </div>
			</div>
			<table className="w-full text-sm text-left text-gray-500 dark:text-gray-400">
				<thead className="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
					<tr>
						
						<th scope="col" className="px-6 py-3">
							fruit name
						</th>
						
					</tr>
				</thead>
				<tbody>
					<tr
						className="bg-white border-b dark:bg-gray-800 dark:border-gray-700 hover:bg-gray-50 dark:hover:bg-gray-600">
						
						<th scope="row" className="px-6 py-4 font-medium text-gray-900 dark:text-white whitespace-nowrap">
							apple
						</th>
						<td className="px-6 py-4">
							<Image src="/apple.png" width="150" height="150"/>
						</td>
						
					
					</tr>
					<tr
						className="bg-white border-b dark:bg-gray-800 dark:border-gray-700 hover:bg-gray-50 dark:hover:bg-gray-600">
						
						<th scope="row" className="px-6 py-4 font-medium text-gray-900 dark:text-white whitespace-nowrap">
							watermelon
						</th>
						<td className="px-6 py-4">
                        <Image src="/watermelon.png" width="150" height="150"/>
						</td>
						
					</tr>
					<tr className="bg-white dark:bg-gray-800 hover:bg-gray-50 dark:hover:bg-gray-600">
						
						<th scope="row" className="px-6 py-4 font-medium text-gray-900 dark:text-white whitespace-nowrap">
							durian
						</th>
						<td className="px-6 py-4">
                        <Image src="/durian.png" width="150" height="150"/>
						</td>
						
					</tr>
				</tbody>
			</table>
		</div>

	        </div>
      </main>

     
    </div>
  )
}
